export const StyleConfig = {
    lightTheme: {
        bg: "#ffffff",
        text_pri: "#222222",
        text_sec: "#455a64",
        text_err: "#c00400",
        text_link_interactive: "#026ebe",
        text_disabled: "#cfd8dc",
        border: "#b0bec5",
        text_inimicode_logo: "#444444",
        bg_flat_hover: "#d3e0eb",
    },
    darkTheme: {
        bg: "#222222",
        text_pri: "#ffffff",
        text_sec: "#b0bec5",
        text_err: "#ffffff",
        text_link_interactive: "#ffffff",
        text_disabled: "#cfd8dc",
        border: "#455a64",
        text_inimicode_logo: "#ffffff",
        bg_flat_hover: "#284d6d",
    },
    spacing: {
        s: "5px",
        m: "16px",
        l: "22px",
        xl: "28px",
    },
    fontSize: {
        s: "12px",
        m: "16px",
        l: "20px",
        xl: "26px",
    },
}